name: Build and Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ $default-branch ]

# ENV and Config
env:
  CONFIG_NODE_VERSION: '["lts/*"]'
  CONFIG_OS: '["ubuntu-latest"]'

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      NODE_VERSION: ${{ steps.set-config.outputs.CONFIG_NODE_VERSION }}
      OS: ${{ steps.set-config.outputs.CONFIG_OS }}

    steps:
      - id: set-config
        run: |
          echo "CONFIG_NODE_VERSION=${{ toJSON(env.CONFIG_NODE_VERSION) }}" >> $GITHUB_OUTPUT
          echo "CONFIG_OS=${{ toJSON(env.CONFIG_OS) }}" >> $GITHUB_OUTPUT
  build:
    name: Build and Test
    needs: config

    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ${{ fromJSON(needs.config.outputs.OS) }}
        NODE_VERSION: ${{ fromJSON(needs.config.outputs.NODE_VERSION) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Build Library
        run: npm run build --if-present
      - name: Run Tests
        run: npm test --if-present
