name: Manual Release
on:
  workflow_dispatch:
    inputs:
      level:
        description: '<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease'
        required: true
        default: 'patch'
      dryRun:
        description: 'DryRun'
        type: boolean
        default: 'false'
jobs:
  config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: 'Create env file'
        run: |
          echo "./.github/workflows/.env" > .env
  prepare:
    needs: config
    runs-on: ubuntu-latest
    name: Test, Build and prepare Release
    steps:
      - name: Check config
        run: |
          "echo ${{ env.CONFIG_NODE_VERSION }}"
  # release:
  #   needs: prepare
  #   name: Test, Build and Release
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       # os: ${{ env.config_os }}
  #       # node-version: ${{ env.config_node-version }}
  #       os: [ ubuntu-latest ]
  #       node-version: [ 16.x ]
  #   steps:
  #     - name: Check config
  #       run: "echo ${{ env.config_node-version }}"
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix['node-version'] }}
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Build Library
  #       run: npm run build --if-present
  #     - name: Run Tests
  #       run: npm test --if-present
  #     - name: Release
  #       uses: cycjimmy/semantic-release-action@v3
  #       with:
  #         dry_run: ${{ github.event.inputs.dryRun == 'true' }}
  #         extra_plugins: |
  #           @semantic-release/changelog
  #           @semantic-release/git
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #         GIT_AUTHOR_NAME: github-actions
  #         GIT_AUTHOR_EMAIL: github-actions@github.com
  #         GIT_COMMITTER_NAME: github-actions
  #         GIT_COMMITTER_EMAIL: github-actions@github.com
  #         CI: true
