name: build
on: push

env:
  CONFIG_JSONe: "{\"oso\":[\"ubuntu-latest\"],\"nodeo\":[\"16.x\"]}"
  CONFIG_JSON: '{\"oso\":\"ubuntu-latest\"}'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=${{ env.CONFIG_JSON }}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ needs.job1.outputs.matrix }}
    steps:
      - name: Config
        run: |
          echo ${{ needs.job1.outputs.matrix }}
          echo ${{ fromJSON(needs.job1.outputs.matrix) }}